// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.DMARCValidator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("host")]
        public string Host { get; set; }

        [JsonProperty("dmarcHost")]
        public string DmarcHost { get; set; }

        [JsonProperty("hasDmarc")]
        public bool? HasDmarc { get; set; }

        [JsonProperty("dmarc_record")]
        public string DmarcRecord { get; set; }

        [JsonProperty("rua")]
        public Rua Rua { get; set; }

        [JsonProperty("ruf")]
        public Rua Ruf { get; set; }

        [JsonProperty("v")]
        public string V { get; set; }

        [JsonProperty("p")]
        public string P { get; set; }

        [JsonProperty("valid")]
        public bool? Valid { get; set; }

        [JsonProperty("isEnforced")]
        public bool? IsEnforced { get; set; }

        [JsonProperty("riskScore")]
        public long? RiskScore { get; set; }

        [JsonProperty("riskLevel")]
        public string RiskLevel { get; set; }
    }

    public partial class Rua
    {
        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("domain")]
        public string Domain { get; set; }

        [JsonProperty("valid")]
        public bool? Valid { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
